module.exports={
  videoGeneration:{
    enabled:true,
    engine:"local-ready"
  },
  imageGeneration:{
    enabled:true,
    engine:"local-ready"
  },
  audioGeneration:{
    enabled:true,
    engine:"local-ready"
  },
  videoEditing:{
    enabled:true,
    engine:"ffmpeg"
  },
  voice:{
    enabled:true,
    engine:"local-ready"
  },
  storyToVideo:{
    enabled:true
  },
  imageToVideo:{
    enabled:true
  },
  characterAnimation:{
    enabled:true
  },
  youtubeAnalysis:{
    enabled:true
  },
  remix:{
    enabled:true,
    mode:"transformative"
  }
};
